### ISSUE TITLE
WP CRON issue since i've deleted all transient

### ISSUE THREAD

**Issue by ifede84** [dartiss/transient-cleaner#20]
Hi!

I've deleted the transient from two different website using your plugin.

Since this in both website WP CRON stop running: i think the two things are related because  server log shows the WP CRON stop running next transient cleaning

I'm not able to restart WP CRON so i've to use ALTERNATE WP CRON

Can you help me?

**Comment by dartiss** [comment]
Closing, as this is being dealt with on wp.org forums (which is the right place for initial support).
